Fix DB init not working

diff --git a/root/etc/cont-init.d/50-config b/root/etc/cont-init.d/50-config
--- a/root/etc/cont-init.d/50-config
+++ b/root/etc/cont-init.d/50-config
@@ -35,7 +35,11 @@ MYSQL_CMD="mysql -u$DB_USER -h$DB_HOST -p$DB_PASS -D$DB_DATABASE"
 TABLE_COUNT=$($MYSQL_CMD -e"SELECT count(*) AS TN FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '$DB_DATABASE'" -sN)
 if [ $TABLE_COUNT -eq "0" ]; then
 	echo "*** DB is empty -> initing!! ***"
-	$MYSQL_CMD < /var/www/html/tables.my.sql
+	$MYSQL_CMD < /usr/share/mrbs/tables.my.sql
+	if [ $? -ne 0 ]; then
+		echo "*** DB init FAILED!! ***"
+		exit 1
+	fi
 fi
 
 # set permissions
